### ISSUE TITLE
Revert dependency updates made between 4.0.0 and 4.1.0

### ISSUE THREAD

**Issue by buffcode** [develar/app-builder#83]
`electron-builder` currently won't upgrade `app-builder`, because the compression modifiers somehow break: https://github.com/electron-userland/electron-builder/pull/6684

As such `electron-builder` is stuck to 4.0.0 and is unable to incorporate other bugfixes such as https://github.com/develar/app-builder/issues/63 (see https://github.com/electron-userland/electron-builder/pull/6710#issuecomment-1180732439).

I propose to revert the dependency changes inflicting problems with AppImages until this can be resolved, in order to unlock the other patches downstream.

Thanks for your consideration!

**Comment by mmaietta** [comment]
CC @develar could you please take a look at this? It'd be great to update electron-builder to latest app-builder but the current release breaks AppImages

**Comment by beyondkmp** [comment]
I think the root cause is that mksquashfs in appimage-13 doesn't support gzip.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5462444/216087349-d5ccabf9-86c4-44f3-b5c3-438e3fa15fa1.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/5462444/216087386-c0e1aeeb-29e1-474f-b260-fb406f7af42f.png">


In https://github.com/electron-userland/electron-builder-binaries/blob/master/zstd-linux.sh:
Why do you set GZIP_SUPPORT to 0 and set COMP_DEFAULT to zstd?
If we don't set these special params, I think it will works well.

**Comment by develar** [comment]
I published `4.2.0`, @mmaietta please update the version in electron-builder.

**Comment by mmaietta** [comment]
@develar I've attempted to update the dependency in electron-builder but mac and linux CI tests are failing. Can you please take a look?
`EACCES` error code is being thrown

MacOS
```
> @electron-builder/monorepo@ ci:test /Users/runner/work/electron-builder/electron-builder
> node ./test/out/helpers/runTests.js

Error: spawn /Users/runner/work/electron-builder/electron-builder/node_modules/.pnpm/app-builder-bin@4.2.0/node_modules/app-builder-bin/mac/app-builder_amd64 EACCES
```

Linux:
```
Error: spawn /project/node_modules/.pnpm/app-builder-bin@4.2.0/node_modules/app-builder-bin/linux/x64/app-builder EACCES
```

PR https://github.com/electron-userland/electron-builder/pull/7774

**Comment by ramiel** [comment]
I need this modification in order to have a working electron-builder. Any news on this?
